### ISSUE TITLE
SC_Menu Crash - Additional Card Info

### ISSUE THREAD

**Issue by kmort1** [boberito/sc_menu#10]
Updated to 1.6 just now and when trying the new Additional Card Info feature, I input my PIN, get a screen with an empty column of information and then SC_Menu closes.

**Comment by boberito** [comment]
Oh and also do this in terminal as well while you crash it.
`log stream --predicate 'subsystem == "com.ttinc.sc-menu"' --debug --info --signpost` 

And then copy paste all that output of the terminal window into a text file too when you send it over.

**Comment by boberito** [comment]
Resolved in 1.7
