### ISSUE TITLE
Feature Request: Ability to disable the "Check for Update" prompt and disable the "Check for Update" button

### ISSUE THREAD

**Issue by cleanbaldy** [boberito/sc_menu#12]
I'd love to use this tool through our MDM to our fleet.  We currently use the Smart Card Utility, but this would be a menu bar item that would help our Service Desk with an instant way for a user to check their smartcard.

All of our users have Standard permissions to their accounts, so I'd love a way to deploy it without it asking the user to check for an update.

We (The MDM team) can control the version and update periodically through CR's, but we don't want the user to be able to click "Check for Update" or be prompted at opening the app to upgrade to the latest version.

**Comment by boberito** [comment]
This can be done.  I feel like this is the type of thing that should ONLY come from mdm.  So if it was restricted to a configuration profile only work (installed from mdm or manually)? 

Using defaults write yadayada would be ignored.

**Comment by boberito** [comment]
Resolved in 1.7
