### ISSUE TITLE
SC Menu Preferences - Launch at Login

### ISSUE THREAD

**Issue by kmortiere-code** [boberito/sc_menu#6]
It seems that the Launch at Login button doesn't work inside the SC Menu Preferences. Workaround is to do it manually via System Settings

**Comment by boberito** [comment]
What version of macOS? Do you get the bubble an item has been added to Launch Items from the system?

I'll be working on sc menu in the next few weeks when I have some free time. So if you give some more details, I may be able to re-create it, fix it and implement the other things I've made note of.

**Comment by kmortiere-code** [comment]
I'm running macOS 14.6.1 (23G93). In order to activate that setting for launch at login I have to manually go into System Settings and add it. At that point it will notify me that a Launch Item was added. But when I try to activate that feature via SC Menu Preferences it doesn't let me click the check bock. Instead, I get the I-beam pointer as if I'm selecting text.

**Comment by boberito** [comment]
Ok crazy. It's happening to me too. I got a chance to try it on a fresh machine.

I'll dig and figure it out sometime soon.
