### ISSUE TITLE
Brew Install Option

### ISSUE THREAD

**Issue by allebone** [boberito/sc_menu#8]
Enhancement Request: Any chance there might be enough interest in including this install via Brew? 

All of our LAN Connected MacOS Machines and Build Servers (MacOS) use brew via ansible for initial and weekly builds.

https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by boberito** [comment]
Someone tried a bit ago actually
`GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)`

:( so it'll be a while.

**Comment by joewiz** [comment]
@allebone I'd love to have SC Menu installable / updateable via Homebrew. Maybe we can get there! Please star / watch the project and encourage others to do so.

**Comment by joewiz** [comment]
@allebone We [did it](https://github.com/Homebrew/homebrew-cask/pull/211059)! Now you can install SC Menu with `brew install sc-menu`.

**Comment by allebone** [comment]
Dudddeee! Thats amazing! Great work! 

Just added it to our normal Ansible Build playbook/role, so when we build our next Mac Cluster, all 16 will get sc-menu without lifting a finger!

Thanks again!

**Comment by boberito** [comment]
@allebone Mac Cluster?! What where? How? Huh?

**Comment by allebone** [comment]
oh we have several. Due to my primary employer, we have to do all of our Builds in an offline state for all of our custom Mobile App Builds; so we build our own Mac Build Clusters. Currently, we're Studio based, but we're in the process of procuring and setting up our first 16 Mac mini M4 cluster under an Internal Project called KAMINO.

Due to STIG requirements, our administrators must use SmartCards for any up close work, so sc-menu is a god-send. You get a little turned around when you're hopping around among a bunch of Macs running as basically headless servers.  "Did the KVM move my Smartcard?" :)
